# Compare test to Stanford dog data

In [1]:
import os
import time
import sys

import skimage.io as skio

import numpy as np

### Stanford images

In [2]:
cwd = os.getcwd()
input_folder = os.path.join(cwd, 'input')
stanford_img_folder = os.path.join(input_folder, 'images')

stanford_img_name_arr = []
stanford_img_part_arr = []

for breed_folder_name in os.listdir(stanford_img_folder):
    breed_folder = os.path.join(stanford_img_folder, breed_folder_name)
    for img_name in os.listdir(breed_folder):
        stanford_img_name_arr.append(breed_folder_name + '/' + img_name)
        img_file = os.path.join(breed_folder, img_name)
        img = skio.imread(img_file)
#         print(img.shape)
        stanford_img_part_arr.append(img[20:90, 80:90, 0].copy())
        del img
print(len(stanford_img_name_arr))
print(len(stanford_img_part_arr))

20580
20580


In [3]:
print(stanford_img_name_arr[0])
print(stanford_img_part_arr[0])

n02085620-Chihuahua/n02085620_10074.jpg
[[155 170 192 212 224 230 234 239 245 244]
 [168 182 201 216 223 228 233 239 234 234]
 [183 195 212 224 229 232 238 245 232 232]
 [193 206 222 234 238 240 246 253 239 236]
 [207 204 214 234 241 235 237 249 248 247]
 [196 205 224 243 246 238 236 243 235 239]
 [209 219 231 236 233 233 238 247 248 245]
 [224 232 236 233 229 232 235 238 248 242]
 [220 230 239 244 245 241 230 219 222 224]
 [227 227 231 239 244 242 234 228 229 227]
 [238 229 225 231 234 233 237 246 252 241]
 [233 227 230 241 239 229 229 242 246 238]
 [220 232 237 231 230 234 234 227 229 233]
 [250 248 246 242 238 231 230 233 234 237]
 [246 236 234 240 237 230 232 244 240 240]
 [222 219 223 231 233 230 234 240 235 233]
 [217 226 233 232 232 233 229 219 227 221]
 [217 229 234 230 230 233 223 209 229 223]
 [212 215 217 220 224 227 223 217 232 226]
 [217 206 205 215 221 218 221 229 223 221]
 [221 228 207 194 211 222 219 224 224 220]
 [173 211 225 213 208 202 205 222 203 208]
 [150 184 207 

### Load train

In [4]:
cwd = os.getcwd()
input_folder = os.path.join(cwd, 'input')
train_img_folder = os.path.join(input_folder, 'train')

train_img_name_arr = []
train_img_part_arr = []

for img_name in os.listdir(train_img_folder):
    train_img_name_arr.append(img_name)
    img_file = os.path.join(train_img_folder, img_name)
    img = skio.imread(img_file)
    train_img_part_arr.append(img[20:90, 80:90, 0].copy())
    del img
    
print(len(train_img_name_arr))
print(len(train_img_part_arr))

10222
10222


In [5]:
print(train_img_name_arr[0])
print(train_img_part_arr[0])

000bec180eb18c7604dcecc8fe0dba07.jpg
[[211 180 180 197 199 205 225 235 219 226]
 [199 190 175 177 200 223 230 231 227 224]
 [173 196 178 164 193 216 220 234 235 234]
 [165 201 187 172 197 202 208 255 237 245]
 [213 181 183 186 199 204 194 234 251 220]
 [201 198 207 205 195 224 207 212 250 241]
 [210 213 210 201 183 211 200 203 151 166]
 [211 212 202 188 196 167 149 174 148 148]
 [196 215 210 183 218 130  94 112 164 172]
 [196 214 202 164 185 106  82  72  83 117]
 [201 171 151 161 119  85  94  70  63  95]
 [186 108  99 188  87  73  95  70  85 129]
 [125  86 153 117  96  92  78  88  95  92]
 [ 74 141 157  87 105 109  89  84  94  98]
 [110 147 108  78 110  86  90 109  97  76]
 [169 109  70  92  97  69  89 112 118 104]
 [140  99  91  89  79  88  86  92 100 127]
 [ 98 109  99  78  74  88  74 119  95  97]
 [ 96  98  76 102  81  75  96 131 122  84]
 [ 93  76  68 140  84  88 142  85  90  79]
 [ 90  94 104 155 128  92 121  88  98  92]
 [115 143 159 176 121  82 117  94  99 102]
 [ 79 114 130 136

### Load test

In [6]:
cwd = os.getcwd()
input_folder = os.path.join(cwd, 'input')
test_img_folder = os.path.join(input_folder, 'test')

test_img_name_arr = []
test_img_part_arr = []

for img_name in os.listdir(test_img_folder):
    test_img_name_arr.append(img_name)
    img_file = os.path.join(test_img_folder, img_name)
    img = skio.imread(img_file)
    test_img_part_arr.append(img[20:90, 20:80, 0].copy())
    del img
    
print(len(test_img_name_arr))
print(len(test_img_part_arr))

10357
10357


In [7]:
print(test_img_name_arr[0])
print(test_img_part_arr[0])

000621fb3cbb32d8935728e48679680e.jpg
[[ 82  96  98 ...,  13  18  46]
 [ 91 121  90 ...,  15  11  41]
 [ 79  99  58 ...,  35  19  31]
 ..., 
 [100  88  98 ..., 105  88  92]
 [105  92  98 ...,  69  78  79]
 [106  83  89 ...,  91 112 104]]


### Compare train to Stanford

In [8]:
k = 0
train_cmp = []
for i, train_img in enumerate(train_img_part_arr):
    temp = []
    for j, s_img in enumerate(stanford_img_part_arr):
        if np.array_equal(train_img, s_img):
            temp.append(stanford_img_name_arr[j])
    if len(temp) > 1:
        print((train_img_name_arr[i], temp), end='\n\n')
    if len(temp) > 0:
        print('-', end='')
        train_cmp.append((train_img_name_arr[i], temp))
#     k += 1
#     if k > 1000:
#         break

print(len(train_cmp))
print(len(train_img_part_arr))
print(len(stanford_img_part_arr))

('04e370c8510638ca969a716822444085.jpg', ['n02087394-Rhodesian_ridgeback/n02087394_4602.jpg', 'n02088364-beagle/n02088364_16588.jpg', 'n02093256-Staffordshire_bullterrier/n02093256_367.jpg', 'n02093647-Bedlington_terrier/n02093647_289.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1136.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1213.jpg', 'n02093859-Kerry_blue_terrier/n02093859_2579.jpg', 'n02093859-Kerry_blue_terrier/n02093859_998.jpg', 'n02094114-Norfolk_terrier/n02094114_3060.jpg', 'n02095570-Lakeland_terrier/n02095570_3534.jpg', 'n02096051-Airedale/n02096051_2333.jpg', 'n02096051-Airedale/n02096051_2432.jpg', 'n02097130-giant_schnauzer/n02097130_2989.jpg', 'n02097130-giant_schnauzer/n02097130_3018.jpg', 'n02097130-giant_schnauzer/n02097130_977.jpg', 'n02097209-standard_schnauzer/n02097209_1923.jpg', 'n02097298-Scotch_terrier/n02097298_3589.jpg', 'n02097298-Scotch_terrier/n02097298_6261.jpg', 'n02099712-Labrador_retriever/n02099712_2234.jpg', 'n02099712-Labrador_retriever/n0209971

-('0a6c192b96e55e2ca37318919b1ffae6.jpg', ['n02092339-Weimaraner/n02092339_353.jpg', 'n02099429-curly-coated_retriever/n02099429_3077.jpg', 'n02106030-collie/n02106030_19103.jpg', 'n02107908-Appenzeller/n02107908_396.jpg', 'n02108915-French_bulldog/n02108915_10204.jpg', 'n02109047-Great_Dane/n02109047_18490.jpg', 'n02110806-basenji/n02110806_1035.jpg', 'n02111277-Newfoundland/n02111277_12022.jpg'])

-('0c1a1b2adfd0aa2fef3eb974b9b95734.jpg', ['n02087394-Rhodesian_ridgeback/n02087394_4602.jpg', 'n02088364-beagle/n02088364_16588.jpg', 'n02093256-Staffordshire_bullterrier/n02093256_367.jpg', 'n02093647-Bedlington_terrier/n02093647_289.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1136.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1213.jpg', 'n02093859-Kerry_blue_terrier/n02093859_2579.jpg', 'n02093859-Kerry_blue_terrier/n02093859_998.jpg', 'n02094114-Norfolk_terrier/n02094114_3060.jpg', 'n02095570-Lakeland_terrier/n02095570_3534.jpg', 'n02096051-Airedale/n02096051_2333.jpg', 'n02096051-Air

-('340c5a6ff260c7896682730385a8d337.jpg', ['n02087394-Rhodesian_ridgeback/n02087394_4602.jpg', 'n02088364-beagle/n02088364_16588.jpg', 'n02093256-Staffordshire_bullterrier/n02093256_367.jpg', 'n02093647-Bedlington_terrier/n02093647_289.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1136.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1213.jpg', 'n02093859-Kerry_blue_terrier/n02093859_2579.jpg', 'n02093859-Kerry_blue_terrier/n02093859_998.jpg', 'n02094114-Norfolk_terrier/n02094114_3060.jpg', 'n02095570-Lakeland_terrier/n02095570_3534.jpg', 'n02096051-Airedale/n02096051_2333.jpg', 'n02096051-Airedale/n02096051_2432.jpg', 'n02097130-giant_schnauzer/n02097130_2989.jpg', 'n02097130-giant_schnauzer/n02097130_3018.jpg', 'n02097130-giant_schnauzer/n02097130_977.jpg', 'n02097209-standard_schnauzer/n02097209_1923.jpg', 'n02097298-Scotch_terrier/n02097298_3589.jpg', 'n02097298-Scotch_terrier/n02097298_6261.jpg', 'n02099712-Labrador_retriever/n02099712_2234.jpg', 'n02099712-Labrador_retriever/n020997

--('416f36e236378210a7b553c0717950d1.jpg', ['n02092339-Weimaraner/n02092339_353.jpg', 'n02099429-curly-coated_retriever/n02099429_3077.jpg', 'n02106030-collie/n02106030_19103.jpg', 'n02107908-Appenzeller/n02107908_396.jpg', 'n02108915-French_bulldog/n02108915_10204.jpg', 'n02109047-Great_Dane/n02109047_18490.jpg', 'n02110806-basenji/n02110806_1035.jpg', 'n02111277-Newfoundland/n02111277_12022.jpg'])

-('42404238339c427c0fb830da89885d5e.jpg', ['n02087394-Rhodesian_ridgeback/n02087394_4602.jpg', 'n02088364-beagle/n02088364_16588.jpg', 'n02093256-Staffordshire_bullterrier/n02093256_367.jpg', 'n02093647-Bedlington_terrier/n02093647_289.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1136.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1213.jpg', 'n02093859-Kerry_blue_terrier/n02093859_2579.jpg', 'n02093859-Kerry_blue_terrier/n02093859_998.jpg', 'n02094114-Norfolk_terrier/n02094114_3060.jpg', 'n02095570-Lakeland_terrier/n02095570_3534.jpg', 'n02096051-Airedale/n02096051_2333.jpg', 'n02096051-Ai

-('59df7d7a2707fb4e77a61d507b68cb07.jpg', ['n02087394-Rhodesian_ridgeback/n02087394_4602.jpg', 'n02088364-beagle/n02088364_16588.jpg', 'n02093256-Staffordshire_bullterrier/n02093256_367.jpg', 'n02093647-Bedlington_terrier/n02093647_289.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1136.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1213.jpg', 'n02093859-Kerry_blue_terrier/n02093859_2579.jpg', 'n02093859-Kerry_blue_terrier/n02093859_998.jpg', 'n02094114-Norfolk_terrier/n02094114_3060.jpg', 'n02095570-Lakeland_terrier/n02095570_3534.jpg', 'n02096051-Airedale/n02096051_2333.jpg', 'n02096051-Airedale/n02096051_2432.jpg', 'n02097130-giant_schnauzer/n02097130_2989.jpg', 'n02097130-giant_schnauzer/n02097130_3018.jpg', 'n02097130-giant_schnauzer/n02097130_977.jpg', 'n02097209-standard_schnauzer/n02097209_1923.jpg', 'n02097298-Scotch_terrier/n02097298_3589.jpg', 'n02097298-Scotch_terrier/n02097298_6261.jpg', 'n02099712-Labrador_retriever/n02099712_2234.jpg', 'n02099712-Labrador_retriever/n020997

--('7f5414cd8c4dfd37f15f176735b2aa39.jpg', ['n02087394-Rhodesian_ridgeback/n02087394_4602.jpg', 'n02088364-beagle/n02088364_16588.jpg', 'n02093256-Staffordshire_bullterrier/n02093256_367.jpg', 'n02093647-Bedlington_terrier/n02093647_289.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1136.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1213.jpg', 'n02093859-Kerry_blue_terrier/n02093859_2579.jpg', 'n02093859-Kerry_blue_terrier/n02093859_998.jpg', 'n02094114-Norfolk_terrier/n02094114_3060.jpg', 'n02095570-Lakeland_terrier/n02095570_3534.jpg', 'n02096051-Airedale/n02096051_2333.jpg', 'n02096051-Airedale/n02096051_2432.jpg', 'n02097130-giant_schnauzer/n02097130_2989.jpg', 'n02097130-giant_schnauzer/n02097130_3018.jpg', 'n02097130-giant_schnauzer/n02097130_977.jpg', 'n02097209-standard_schnauzer/n02097209_1923.jpg', 'n02097298-Scotch_terrier/n02097298_3589.jpg', 'n02097298-Scotch_terrier/n02097298_6261.jpg', 'n02099712-Labrador_retriever/n02099712_2234.jpg', 'n02099712-Labrador_retriever/n02099

-('861dee51881dc7a69672f63d5370f4a7.jpg', ['n02092339-Weimaraner/n02092339_353.jpg', 'n02099429-curly-coated_retriever/n02099429_3077.jpg', 'n02106030-collie/n02106030_19103.jpg', 'n02107908-Appenzeller/n02107908_396.jpg', 'n02108915-French_bulldog/n02108915_10204.jpg', 'n02109047-Great_Dane/n02109047_18490.jpg', 'n02110806-basenji/n02110806_1035.jpg', 'n02111277-Newfoundland/n02111277_12022.jpg'])

-('89714899135c134b326fecdd2c2647b0.jpg', ['n02087394-Rhodesian_ridgeback/n02087394_4602.jpg', 'n02088364-beagle/n02088364_16588.jpg', 'n02093256-Staffordshire_bullterrier/n02093256_367.jpg', 'n02093647-Bedlington_terrier/n02093647_289.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1136.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1213.jpg', 'n02093859-Kerry_blue_terrier/n02093859_2579.jpg', 'n02093859-Kerry_blue_terrier/n02093859_998.jpg', 'n02094114-Norfolk_terrier/n02094114_3060.jpg', 'n02095570-Lakeland_terrier/n02095570_3534.jpg', 'n02096051-Airedale/n02096051_2333.jpg', 'n02096051-Air

-('9951edcf2d8205b7ddc7933f93b3bb24.jpg', ['n02094114-Norfolk_terrier/n02094114_2955.jpg', 'n02113712-miniature_poodle/n02113712_48.jpg'])

-('9baf45e1dffbf945d7390de180a631da.jpg', ['n02087394-Rhodesian_ridgeback/n02087394_4602.jpg', 'n02088364-beagle/n02088364_16588.jpg', 'n02093256-Staffordshire_bullterrier/n02093256_367.jpg', 'n02093647-Bedlington_terrier/n02093647_289.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1136.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1213.jpg', 'n02093859-Kerry_blue_terrier/n02093859_2579.jpg', 'n02093859-Kerry_blue_terrier/n02093859_998.jpg', 'n02094114-Norfolk_terrier/n02094114_3060.jpg', 'n02095570-Lakeland_terrier/n02095570_3534.jpg', 'n02096051-Airedale/n02096051_2333.jpg', 'n02096051-Airedale/n02096051_2432.jpg', 'n02097130-giant_schnauzer/n02097130_2989.jpg', 'n02097130-giant_schnauzer/n02097130_3018.jpg', 'n02097130-giant_schnauzer/n02097130_977.jpg', 'n02097209-standard_schnauzer/n02097209_1923.jpg', 'n02097298-Scotch_terrier/n02097298_3589.j

--('b36db4c42629a8fda912011e967d9f8a.jpg', ['n02087394-Rhodesian_ridgeback/n02087394_4602.jpg', 'n02088364-beagle/n02088364_16588.jpg', 'n02093256-Staffordshire_bullterrier/n02093256_367.jpg', 'n02093647-Bedlington_terrier/n02093647_289.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1136.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1213.jpg', 'n02093859-Kerry_blue_terrier/n02093859_2579.jpg', 'n02093859-Kerry_blue_terrier/n02093859_998.jpg', 'n02094114-Norfolk_terrier/n02094114_3060.jpg', 'n02095570-Lakeland_terrier/n02095570_3534.jpg', 'n02096051-Airedale/n02096051_2333.jpg', 'n02096051-Airedale/n02096051_2432.jpg', 'n02097130-giant_schnauzer/n02097130_2989.jpg', 'n02097130-giant_schnauzer/n02097130_3018.jpg', 'n02097130-giant_schnauzer/n02097130_977.jpg', 'n02097209-standard_schnauzer/n02097209_1923.jpg', 'n02097298-Scotch_terrier/n02097298_3589.jpg', 'n02097298-Scotch_terrier/n02097298_6261.jpg', 'n02099712-Labrador_retriever/n02099712_2234.jpg', 'n02099712-Labrador_retriever/n02099

-('b76ab109cca8b7170e7b8983dfc1c9db.jpg', ['n02087394-Rhodesian_ridgeback/n02087394_4602.jpg', 'n02088364-beagle/n02088364_16588.jpg', 'n02093256-Staffordshire_bullterrier/n02093256_367.jpg', 'n02093647-Bedlington_terrier/n02093647_289.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1136.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1213.jpg', 'n02093859-Kerry_blue_terrier/n02093859_2579.jpg', 'n02093859-Kerry_blue_terrier/n02093859_998.jpg', 'n02094114-Norfolk_terrier/n02094114_3060.jpg', 'n02095570-Lakeland_terrier/n02095570_3534.jpg', 'n02096051-Airedale/n02096051_2333.jpg', 'n02096051-Airedale/n02096051_2432.jpg', 'n02097130-giant_schnauzer/n02097130_2989.jpg', 'n02097130-giant_schnauzer/n02097130_3018.jpg', 'n02097130-giant_schnauzer/n02097130_977.jpg', 'n02097209-standard_schnauzer/n02097209_1923.jpg', 'n02097298-Scotch_terrier/n02097298_3589.jpg', 'n02097298-Scotch_terrier/n02097298_6261.jpg', 'n02099712-Labrador_retriever/n02099712_2234.jpg', 'n02099712-Labrador_retriever/n020997

--('c3ffe489a6dd65d192c0d839ded36e94.jpg', ['n02094114-Norfolk_terrier/n02094114_2955.jpg', 'n02113712-miniature_poodle/n02113712_48.jpg'])

-('ce92370c283c12eb64271cdec81fc1d5.jpg', ['n02094114-Norfolk_terrier/n02094114_2955.jpg', 'n02113712-miniature_poodle/n02113712_48.jpg'])

-('cf0b75d1f10ab79d91069820c99dc4fa.jpg', ['n02092339-Weimaraner/n02092339_353.jpg', 'n02099429-curly-coated_retriever/n02099429_3077.jpg', 'n02106030-collie/n02106030_19103.jpg', 'n02107908-Appenzeller/n02107908_396.jpg', 'n02108915-French_bulldog/n02108915_10204.jpg', 'n02109047-Great_Dane/n02109047_18490.jpg', 'n02110806-basenji/n02110806_1035.jpg', 'n02111277-Newfoundland/n02111277_12022.jpg'])

-('d5b98aa5af9ecf0987b25921ee09ccaa.jpg', ['n02087394-Rhodesian_ridgeback/n02087394_4602.jpg', 'n02088364-beagle/n02088364_16588.jpg', 'n02093256-Staffordshire_bullterrier/n02093256_367.jpg', 'n02093647-Bedlington_terrier/n02093647_289.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1136.jpg', 'n02093859-Kerry_blue_t

--('f31950a05e0c02c69042b6d3bcb3682d.jpg', ['n02087394-Rhodesian_ridgeback/n02087394_4602.jpg', 'n02088364-beagle/n02088364_16588.jpg', 'n02093256-Staffordshire_bullterrier/n02093256_367.jpg', 'n02093647-Bedlington_terrier/n02093647_289.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1136.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1213.jpg', 'n02093859-Kerry_blue_terrier/n02093859_2579.jpg', 'n02093859-Kerry_blue_terrier/n02093859_998.jpg', 'n02094114-Norfolk_terrier/n02094114_3060.jpg', 'n02095570-Lakeland_terrier/n02095570_3534.jpg', 'n02096051-Airedale/n02096051_2333.jpg', 'n02096051-Airedale/n02096051_2432.jpg', 'n02097130-giant_schnauzer/n02097130_2989.jpg', 'n02097130-giant_schnauzer/n02097130_3018.jpg', 'n02097130-giant_schnauzer/n02097130_977.jpg', 'n02097209-standard_schnauzer/n02097209_1923.jpg', 'n02097298-Scotch_terrier/n02097298_3589.jpg', 'n02097298-Scotch_terrier/n02097298_6261.jpg', 'n02099712-Labrador_retriever/n02099712_2234.jpg', 'n02099712-Labrador_retriever/n02099

In [9]:
for d in train_cmp[:20]:
    print(d)

('04e370c8510638ca969a716822444085.jpg', ['n02087394-Rhodesian_ridgeback/n02087394_4602.jpg', 'n02088364-beagle/n02088364_16588.jpg', 'n02093256-Staffordshire_bullterrier/n02093256_367.jpg', 'n02093647-Bedlington_terrier/n02093647_289.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1136.jpg', 'n02093859-Kerry_blue_terrier/n02093859_1213.jpg', 'n02093859-Kerry_blue_terrier/n02093859_2579.jpg', 'n02093859-Kerry_blue_terrier/n02093859_998.jpg', 'n02094114-Norfolk_terrier/n02094114_3060.jpg', 'n02095570-Lakeland_terrier/n02095570_3534.jpg', 'n02096051-Airedale/n02096051_2333.jpg', 'n02096051-Airedale/n02096051_2432.jpg', 'n02097130-giant_schnauzer/n02097130_2989.jpg', 'n02097130-giant_schnauzer/n02097130_3018.jpg', 'n02097130-giant_schnauzer/n02097130_977.jpg', 'n02097209-standard_schnauzer/n02097209_1923.jpg', 'n02097298-Scotch_terrier/n02097298_3589.jpg', 'n02097298-Scotch_terrier/n02097298_6261.jpg', 'n02099712-Labrador_retriever/n02099712_2234.jpg', 'n02099712-Labrador_retriever/n0209971

In [10]:
k = 0
test_cmp = []
for i, test_img in enumerate(test_img_part_arr):
    temp = []
    for j, s_img in enumerate(stanford_img_part_arr):
        if np.array_equal(test_img, s_img):
            temp.append(stanford_img_name_arr[j])
    if len(temp) > 1:
        print((test_img_name_arr[i], temp), end='\n\n')
    if len(temp) > 0:
        print('-', end='')
        test_cmp.append((test_img_name_arr[i], temp))
#     k += 1
#     if k > 1000:
#         break

print(len(test_cmp))
print(len(test_img_part_arr))
print(len(stanford_img_part_arr))

0
10357
20580


In [11]:
for d in test_cmp[:20]:
    print(d)

In [12]:
print(np.array_equal([1,2,3], [1,2,3]))
print(np.array_equal([1,2,3], [1,2,4]))

True
False
