## Demo_faiss

Abstract:
- [facebook Faiss的基本使用示例(逐步深入）](https://blog.csdn.net/sparkexpert/article/details/68922307)

In [1]:
import numpy as np
d = 64
nb = 100000
nq = 10000
np.random.seed(1234)
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

In [2]:
import faiss
indx = faiss.IndexFlatL2(d)
print(indx.is_trained)
indx.add(xb)
print(indx.ntotal)

True
100000


In [3]:
k = 4
D, I = indx.search(xb[:5], k)
print(D)
print(I)
D, I = indx.search(xq[:5], k)
print(D)
print(I)

[[0.        7.1751738 7.20763   7.2511625]
 [0.        6.3235645 6.684581  6.799946 ]
 [0.        5.7964087 6.391736  7.2815123]
 [0.        7.2779055 7.527987  7.6628466]
 [0.        6.7638035 7.2951202 7.3688145]]
[[  0 393 363  78]
 [  1 555 277 364]
 [  2 304 101  13]
 [  3 173  18 182]
 [  4 288 370 531]]
[[6.8155107 6.889466  7.3956785 7.429021 ]
 [6.604111  6.6797004 6.7209654 6.82868  ]
 [6.470383  6.8578625 7.0043745 7.036566 ]
 [5.573686  6.4075484 7.1395154 7.3555965]
 [5.409403  6.232215  6.4173393 6.5743637]]
[[ 381  207  210  477]
 [ 526  911  142   72]
 [ 838  527 1290  425]
 [ 196  184  164  359]
 [ 526  377  120  425]]


In [11]:
minlength = 6
y = list(map(lambda n: n if n <= minlength else 0, D.reshape(-1)))
ii = np.nonzero(y)[0]
print(y)
print(ii)
print(I.reshape(-1)[ii])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5.573686, 0, 0, 0, 5.409403, 0, 0, 0]
[12 16]
[196 526]
