## Demo_np_bincount

Reference:
- https://docs.scipy.org/doc/numpy/reference/generated/numpy.bincount.html

In [1]:
import numpy as np
x = np.array([1, 1, 1, 2, 2, 2, 5, 25, 1, 1])
y = np.bincount(x)
ii = np.nonzero(y)[0]
print(y)
print(ii)

[0 5 3 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[ 1  2  5 25]


In [2]:
# minlength do not work
x = np.array([0, 0, 0, 1, 1, 3, 2, 1, 2, 2, 1, 1, 7])
y = np.bincount(x, minlength=4)
ii = np.nonzero(y)[0]
print(y)
print(ii)

[3 5 3 1 0 0 0 1]
[0 1 2 3 7]


In [3]:
# use map to implemente this minlength
minlength = 3
x = np.array([0, 0, 1, 1, 3, 2, 1, 2, 2, 1, 1, 7, 7, 7])
y = np.bincount(x)
y = list(map(lambda n: n if n >= minlength else 0, y))
ii = np.nonzero(y)[0]
print(y)
print(ii)

[0, 5, 3, 0, 0, 0, 0, 3]
[1 2 7]
